name: Build Add-on

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build addon
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get addon information
        id: info
        uses: home-assistant/actions/helpers/info@master
        with:
          path: "./addon"

      - name: Build addon
        uses: home-assistant/builder@master
        with:
          args: |
            --all \
            --target addon \
            --addon
